#ifndef CONTROLS
#define CONTROLS

#define RIGHT_TRIGGER 0
#define EXPLOSION_TRIGGER 3
#define CLIMB_TRIGGER 4
#define JUMP_TRIGGER 5
#define LIGHT_TRIGGER 6
#define LEFT_TRIGGER 7
#define HAIR_TRIGGER 1

#define SKIP_VALUE 0x81


#endif // CONTROLS